import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const gamesSrc = fs.readFileSync(path.join(__dirname, "..", "src", "lib", "games.ts"), "utf8");
const slugs = [...new Set([...gamesSrc.matchAll(/slug: "([^"]+)"/g)].map((m) => m[1]))];

/** @type {Record<string, string>} */
const genreMap = {
  "the-witcher-3": "Action RPG",
  "fallout-4": "Action RPG",
  "metal-gear-solid-v": "Action-Adventure",
  "batman-arkham-knight": "Action-Adventure",
  "star-wars-battlefront-2015": "Shooter",
  "just-cause-3": "Open World",
  "mad-max": "Open World",
  "assassins-creed-syndicate": "Open World",
  "call-of-duty-black-ops-3": "FPS",
  "rainbow-six-siege": "FPS",
  "battlefield-hardline": "FPS",
  "grand-theft-auto-v": "Open World",
  "dying-light": "Survival",
  "mortal-kombat-x": "Fighting",
  "project-cars": "Racing",
  "life-is-strange": "Adventure",
  "doom-2016": "FPS",
  "dark-souls-3": "Action RPG",
  "overwatch": "Shooter",
  "dishonored-2": "Action-Adventure",
  "titanfall-2": "FPS",
  "battlefield-1": "FPS",
  "watch-dogs-2": "Open World",
  "deus-ex-mankind-divided": "RPG",
  "hitman-2016": "Action-Adventure",
  "rise-of-the-tomb-raider": "Action-Adventure",
  "the-division": "Shooter",
  "mirrors-edge-catalyst": "Action-Adventure",
  "quantum-break": "Action-Adventure",
  "gears-of-war-4": "Shooter",
  "civilization-vi": "Strategy",
  "xcom-2": "Strategy",
  "total-war-warhammer": "Strategy",
  "no-mans-sky": "Open World",
  "forza-horizon-3": "Racing",
  "mafia-3": "Open World",
  "resident-evil-7": "Horror",
  "mass-effect-andromeda": "Action RPG",
  "prey-2017": "Action-Adventure",
  "destiny-2": "Shooter",
  "assassins-creed-origins": "Open World",
  "wolfenstein-2": "FPS",
  "call-of-duty-wwii": "FPS",
  "star-wars-battlefront-2": "Shooter",
  "for-honor": "Fighting",
  "nier-automata": "Action RPG",
  "middle-earth-shadow-of-war": "Open World",
  "tekken-7": "Fighting",
  "pubg": "Battle Royale",
  "fortnite": "Battle Royale",
  "hellblade-senuas-sacrifice": "Action-Adventure",
  "sonic-forces": "Platformer",
  "cuphead": "Platformer",
  "south-park-fractured-but-whole": "RPG",
  "need-for-speed-payback": "Racing",
  "monster-hunter-world": "Action RPG",
  "far-cry-5": "Open World",
  "shadow-of-the-tomb-raider": "Action-Adventure",
  "assassins-creed-odyssey": "Open World",
  "battlefield-v": "FPS",
  "call-of-duty-black-ops-4": "FPS",
  "sea-of-thieves": "Adventure",
  "state-of-decay-2": "Survival",
  "hitman-2": "Action-Adventure",
  "just-cause-4": "Open World",
  "dragon-quest-xi": "RPG",
  "soulcalibur-vi": "Fighting",
  "vampyr": "Action RPG",
  "a-way-out": "Adventure",
  "spyro-reignited-trilogy": "Platformer",
  "anthem": "Action RPG",
  "sekiro": "Action RPG",
  "metro-exodus": "FPS",
  "control": "Action-Adventure",
  "borderlands-3": "Shooter",
  "call-of-duty-modern-warfare-2019": "FPS",
  "resident-evil-2-remake": "Horror",
  "devil-may-cry-5": "Action-Adventure",
  "gears-5": "Shooter",
  "the-outer-worlds": "RPG",
  "star-wars-jedi-fallen-order": "Action-Adventure",
  "wolfenstein-youngblood": "FPS",
  "rage-2": "Open World",
  "the-division-2": "Shooter",
  "apex-legends": "Battle Royale",
  "remnant-from-the-ashes": "Shooter",
  "crash-team-racing-nitro-fueled": "Racing",
  "doom-eternal": "FPS",
  "cyberpunk-2077": "Action RPG",
  "half-life-alyx": "FPS",
  "assassins-creed-valhalla": "Open World",
  "watch-dogs-legion": "Open World",
  "call-of-duty-black-ops-cold-war": "FPS",
  "marvels-avengers": "Action RPG",
  "microsoft-flight-simulator": "Simulation",
  "death-stranding": "Open World",
  "horizon-zero-dawn": "Action RPG",
  "red-dead-redemption-2": "Open World",
  "resident-evil-3-remake": "Horror",
  "ghostrunner": "Action-Adventure",
  "immortals-fenyx-rising": "Open World",
  "dirt-5": "Racing",
  "mafia-definitive-edition": "Open World",
  "yakuza-like-a-dragon": "RPG",
  "resident-evil-village": "Horror",
  "far-cry-6": "Open World",
  "halo-infinite": "FPS",
  "battlefield-2042": "FPS",
  "forza-horizon-5": "Racing",
  "psychonauts-2": "Platformer",
  "guardians-of-the-galaxy": "Action-Adventure",
  "back-4-blood": "Shooter",
  "deathloop": "FPS",
  "kena-bridge-of-spirits": "Action-Adventure",
  "hitman-3": "Action-Adventure",
  "outriders": "Shooter",
  "biomutant": "Action RPG",
  "new-world": "Action RPG",
  "age-of-empires-4": "Strategy",
  "call-of-duty-vanguard": "FPS",
  "mass-effect-legendary-edition": "Action RPG",
  "days-gone": "Survival",
  "nier-replicant": "Action RPG",
  "ratchet-clank-rift-apart": "Platformer",
  "elden-ring": "Action RPG",
  "god-of-war": "Action-Adventure",
  "call-of-duty-modern-warfare-2-2022": "FPS",
  "spider-man-remastered": "Open World",
  "uncharted-legacy-of-thieves": "Action-Adventure",
  "dying-light-2": "Survival",
  "ghostwire-tokyo": "Action-Adventure",
  "tiny-tinas-wonderlands": "Shooter",
  "sniper-elite-5": "FPS",
  "total-war-warhammer-3": "Strategy",
  "lego-star-wars-skywalker-saga": "Adventure",
  "sonic-frontiers": "Platformer",
  "stray": "Adventure",
  "gotham-knights": "Action RPG",
  "the-callisto-protocol": "Horror",
  "plague-tale-requiem": "Adventure",
  "f1-22": "Racing",
  "ea-sports-fc-23": "Sports",
  "hogwarts-legacy": "Action RPG",
  "starfield": "Action RPG",
  "baldurs-gate-3": "RPG",
  "alan-wake-2": "Horror",
  "diablo-4": "Action RPG",
  "lies-of-p": "Action RPG",
  "armored-core-6": "Action-Adventure",
  "avatar-frontiers-of-pandora": "Open World",
  "call-of-duty-modern-warfare-3-2023": "FPS",
  "street-fighter-6": "Fighting",
  "remnant-2": "Shooter",
  "dead-space-2023": "Horror",
  "resident-evil-4-remake": "Horror",
  "the-last-of-us-part-1": "Action-Adventure",
  "lords-of-the-fallen-2023": "Action RPG",
  "like-a-dragon-gaiden": "Action-Adventure",
  "payday-3": "FPS",
  "forza-motorsport-2023": "Racing",
  "assassins-creed-mirage": "Action-Adventure",
  "star-wars-jedi-survivor": "Action-Adventure",
  "atomic-heart": "FPS",
  "final-fantasy-xvi": "Action RPG",
  "helldivers-2": "Shooter",
  "dragons-dogma-2": "Action RPG",
  "black-myth-wukong": "Action RPG",
  "star-wars-outlaws": "Open World",
  "indiana-jones-great-circle": "Action-Adventure",
  "hellblade-2": "Action-Adventure",
  "prince-of-persia-lost-crown": "Platformer",
  "tekken-8": "Fighting",
  "alone-in-the-dark-2024": "Horror",
  "persona-3-reload": "RPG",
  "silent-hill-2-remake": "Horror",
  "call-of-duty-black-ops-6": "FPS",
  "metaphor-refantazio": "RPG",
  "space-marine-2": "Shooter",
  "avowed": "RPG",
  "kingdom-come-deliverance-2": "RPG",
  "granblue-fantasy-relink": "Action RPG",
  "ghost-of-tsushima": "Open World",
  "until-dawn-remake": "Horror",
  "stellar-blade": "Action-Adventure",
  "monster-hunter-wilds": "Action RPG",
  "assassins-creed-shadows": "Open World",
  "doom-the-dark-ages": "FPS",
  "clair-obscur-expedition-33": "RPG",
  "split-fiction": "Adventure",
  "mafia-the-old-country": "Open World",
  "civilization-vii": "Strategy",
  "borderlands-4": "Shooter",
  "death-stranding-2": "Open World",
  "ninja-gaiden-4": "Action-Adventure",
};

const missing = slugs.filter((slug) => !genreMap[slug]);
const extra = Object.keys(genreMap).filter((slug) => !slugs.includes(slug));

if (missing.length) {
  console.error("Missing genres:", missing);
  process.exit(1);
}
if (extra.length) {
  console.error("Extra slugs:", extra);
  process.exit(1);
}

const genreOrder = [
  "Action RPG",
  "Action-Adventure",
  "Adventure",
  "Battle Royale",
  "Fighting",
  "FPS",
  "Horror",
  "Open World",
  "Platformer",
  "Racing",
  "RPG",
  "Shooter",
  "Simulation",
  "Sports",
  "Strategy",
  "Survival",
];

const lines = [
  `export type GameGenre =`,
  `  | ${genreOrder.map((g) => `"${g}"`).join("\n  | ")};`,
  "",
  "export const gameGenres: GameGenre[] = [",
  ...genreOrder.map((g) => `  "${g}",`),
  "];",
  "",
  "export const gameGenreBySlug: Record<string, GameGenre> = {",
  ...slugs.map((slug) => `  "${slug}": "${genreMap[slug]}",`),
  "};",
  "",
  "export function getGameGenre(slug: string): GameGenre {",
  '  return gameGenreBySlug[slug] ?? "Action-Adventure";',
  "}",
  "",
];

fs.writeFileSync(path.join(__dirname, "..", "src", "lib", "game-genres.ts"), lines.join("\n"));
console.log(`Wrote ${slugs.length} genres`);
